version: "3.8"
services:
  main:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    depends_on:
      - binance-service
      - kraken-service
      - cbpro-service
      - bitget-service
      - mexc-service
      - kucoin-service
    environment:
      DATABASE_URL: sqlite:///./data/test.db
      SECRET_KEY: your_super_secret_key
  binance-service:
    build:
      context: ./services/binance
      dockerfile: Dockerfile
    container_name: binance-service
    ports:
      - "8001:8001"
    environment:
      BINANCE_API_KEY: your_binance_api_key
      BINANCE_SECRET_KEY: your_binance_secret_key
  kraken-service:
    build:
      context: ./services/kraken
      dockerfile: Dockerfile
    container_name: kraken-service
    ports:
      - "8002:8002"
    environment:
      KRAKEN_API_KEY: your_kraken_api_key
      KRAKEN_SECRET_KEY: your_kraken_secret_key
  cbpro-service:
    build:
      context: ./services/cbpro
      dockerfile: Dockerfile
    container_name: cbpro-service
    ports:
      - "8003:8003"
    environment:
      CBPRO_API_KEY: your_cbpro_api_key
      CBPRO_SECRET_KEY: your_cbpro_secret_key
      CBPRO_PASSPHRASE: your_cbpro_passphrase
  bitget-service:
    build:
      context: ./services/bitget
      dockerfile: Dockerfile
    container_name: bitget-service
    ports:
      - "8004:8004"
    environment:
      BITGET_API_KEY: your_bitget_api_key
      BITGET_SECRET_KEY: your_bitget_secret_key
      BITGET_PASSPHRASE: your_bitget_passphrase
  mexc-service:
    build:
      context: ./services/mexc
      dockerfile: Dockerfile
    container_name: mexc-service
    ports:
      - "8005:8005"
    environment:
      MEXC_API_KEY: your_mexc_api_key
      MEXC_SECRET_KEY: your_mexc_secret_key
  kucoin-service:
    build:
      context: ./services/kucoin
      dockerfile: Dockerfile
    container_name: kucoin-service
    ports:
      - "8006:8006"
    environment:
      KUCOIN_API_KEY: your_kucoin_api_key
      KUCOIN_SECRET_KEY: your_kucoin_secret_key
      KUCOIN_API_PASSPHRASE: your_kucoin_passphrase 